# This is a LaTeX workflow for automatically compiling the report

name: LaTeX
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./report/src

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install latexmk
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive-latex-extra texlive-fonts-extra texlive-bibtex-extra biber
      - name: Install Python dependencies on Ubuntu
        run: sudo apt-get install -y python3-pygments
      - name: Install Pygments
        run: |
          pip install --upgrade Pygments
          pip show pygments

      # Runs latex script
      - name: Compile LaTeX
        run: |
          latexmk main.tex -pdf -shell-escape -synctex=1 -interaction=nonstopmode -f
          biber main
          latexmk main.tex -pdf -shell-escape -synctex=1 -interaction=nonstopmode -f
          latexmk main.tex -pdf -shell-escape -synctex=1 -interaction=nonstopmode -f
          dir

      # Push to repository
      - name: Push to repo
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add main.pdf
          git commit -m "Added by GitHub Action"
          git push
