name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  qodana:
    if: github.actor != 'dependabot[bot]'   # ignore the pull request if it's from Dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
